services:
  nowplaying-color-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      # Flask configuration
      SECRET_KEY: ${SECRET_KEY}
      HOST: ${HOST}
      PORT: ${PORT}
      FLASK_DEBUG: ${FLASK_DEBUG}

      # Encryption configuration
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}

      # Spotify API configuration (optionnel)
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}

      # DB configuration
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}

      # SMTP configuration (not used for now)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - spotify_data:/home/spotifyapi/data
    networks:
      - spotify-network

volumes:
  spotify_data:
