services:
  melodyhue-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${container_name}"
    restart: unless-stopped
    ports:
      - "8494:8494"
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      HOST: "0.0.0.0"
      PORT: "8494"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
      DB_HOST: "${DB_HOST}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT:-5432}"
      SMTP_HOST: "${SMTP_HOST:-}"
      SMTP_PORT: "${SMTP_PORT:-}"
      SMTP_USER: "${SMTP_USER:-}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:-}"
    volumes:
      - melodyhue_data:/home/melodyhue/data
    networks:
      - melodyhue-network

volumes:
  melodyhue_data:

networks:
  melodyhue-network: {}
