line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "W", "I"]
ignore = [
    # Long lines tolerated for inline HTML and f-strings
    "E501",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
